In [ ]:
import pandas as pd

apt = pd.read_excel('C:/Users/user/Desktop/데이터들/아파트_2호선_전체(2022-2026).xlsx')
op = pd.read_excel('C:/Users/user/Desktop/데이터들/오피스텔_2호선_전체(2022-2026).xlsx')
dan = pd.read_excel('C:/Users/user/Desktop/데이터들/단독다가구_2호선_전체(2022-2026).xlsx')
yun = pd.read_excel('C:/Users/user/Desktop/데이터들/연립다세대_2호선_전체(2022-2026).xlsx')

In [2]:
rent = pd.read_excel('C:/Users/user/Desktop/데이터들/전월세가_2022_2026_2호선_통합.xlsx')

In [3]:
rent.columns

Index(['접수년도', '자치구명', '법정동명', '계약일', '전월세구분', '보증금(만원)', '임대료(만원)', '건물용도',
       '역명(2호선)'],
      dtype='str')

In [8]:
rent['역명(2호선)'].unique()

<StringArray>
[            '선릉',          '역삼/강남',          '삼성/선릉',            '까치산',
   '낙성대/서울대입구/봉천',         '신림/신대방',           '건대입구',          '구의/강변',
 '구로디지털단지/대림/도림천',            '신도림',             '용두',            '신설동',
             '사당',           '홍대입구',             '아현',             '합정',
          '신촌/이대',            '충정로',             '신촌',          '교대/서초',
             '방배',          '용답/신답',            '왕십리',            '한양대',
          '뚝섬/성수',           '상왕십리',  '잠실나루/잠실/종합운동장',           '잠실새내',
  '양천구청/신정네거리/용왕',       '영등포구청/당산',             '대림',             '문래',
             '신당',             '시청',          '을지로4가',      '동대문역사문화공원']
Length: 36, dtype: str

In [9]:
apt['역명'].unique()

<StringArray>
[     '용두',      '교대',     '신도림',    '잠실나루',     '신대방',      '성수',     '왕십리',
      '삼성',      '봉천',      '강남',      '당산',    '양천구청',     '까치산',      '사당',
      '신당',      '잠실',      '신림',      '방배',      '구의',    '건대입구', '구로디지털단지',
      '대림',      '아현',   '영등포구청',      '이대',      '합정',      '문래',     '한양대',
      '시청',    '상왕십리',     '신설동',      '용답',    '홍대입구',     '충정로']
Length: 34, dtype: str

In [10]:
set(rent['역명(2호선)'].unique()) & set(apt['역명'].unique())

{'건대입구',
 '까치산',
 '대림',
 '문래',
 '방배',
 '사당',
 '상왕십리',
 '시청',
 '신당',
 '신도림',
 '신설동',
 '아현',
 '왕십리',
 '용두',
 '충정로',
 '한양대',
 '합정',
 '홍대입구'}

In [11]:
set(rent['역명(2호선)'].unique()) - set(apt['역명'].unique())

{'교대/서초',
 '구로디지털단지/대림/도림천',
 '구의/강변',
 '낙성대/서울대입구/봉천',
 '동대문역사문화공원',
 '뚝섬/성수',
 '삼성/선릉',
 '선릉',
 '신림/신대방',
 '신촌',
 '신촌/이대',
 '양천구청/신정네거리/용왕',
 '역삼/강남',
 '영등포구청/당산',
 '용답/신답',
 '을지로4가',
 '잠실나루/잠실/종합운동장',
 '잠실새내'}

In [13]:
set(apt['역명'].unique()) - set(rent['역명(2호선)'].unique())

{'강남',
 '교대',
 '구로디지털단지',
 '구의',
 '당산',
 '봉천',
 '삼성',
 '성수',
 '신대방',
 '신림',
 '양천구청',
 '영등포구청',
 '용답',
 '이대',
 '잠실',
 '잠실나루'}

In [20]:
import glob
import os

folder_path = 'C:/Users/user/Desktop/데이터들/subway'

file_list = glob.glob(os.path.join(folder_path, '*.csv'))

print(file_list)
print('파일 개수:', len(file_list))

['C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_2022.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202301.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202302.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202303.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202304.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202305.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202306.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202307.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202308.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202309.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202310.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202311.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202312.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202401.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202402.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202403.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202404.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202405.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202406.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202407.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202408.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202409.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202410.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202411.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202412.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202501.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202502.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202503.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202504.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202505.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202506.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202507.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202508.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202509.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202510.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202511.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202512.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202601.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202602.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202603.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202604.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202605.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202606.csv', 'C:/Users/user/Desktop/데이터들/subway\\CARD_SUBWAY_MONTH_202607.csv', 'C:/Users/user/Desktop/데이터들/subway\\~$CARD_SUBWAY_MONTH_2022.csv', 'C:/Users/user/Desktop/데이터들/subway\\~$CARD_SUBWAY_MONTH_202301.csv']
파일 개수: 46

In [36]:
test = pd.read_csv(
    'C:/Users/user/Desktop/데이터들/subway/CARD_SUBWAY_MONTH_2022.csv',
    encoding='cp949',
    index_col=False
)

In [43]:
import pandas as pd
import glob
import os

folder_path = 'C:/Users/user/Desktop/데이터들/subway'

file_list = glob.glob(os.path.join(folder_path, '*.csv'))

df_list = []

for file in file_list:

    # 기존에 만든 통합 파일은 제외
    if 'subway_2호선_통합' in os.path.basename(file):
        continue

    df = None

    # 인코딩 자동 확인
    for encoding in ['utf-8-sig', 'utf-8', 'cp949', 'euc-kr']:
        try:
            df = pd.read_csv(
                file,
                encoding=encoding,
                index_col=False
            )
            print(f'{os.path.basename(file)} → {encoding}')
            break
        except UnicodeDecodeError:
            continue

    if df is None:
        print(f'읽기 실패: {file}')
        continue

    # 노선명 컬럼이 없는 파일 제외
    if '노선명' not in df.columns:
        print(f'노선명 없음 → {os.path.basename(file)}')
        continue

    # 2호선만 추출
    df = df[df['노선명'].astype(str).str.strip() == '2호선'].copy()

    if df.empty:
        continue

    # 사용일자에서 연도 추출
    df['연도'] = df['사용일자'].astype(str).str[:4]

    # 필요한 컬럼만 남기기
    df = df[
        [
            '연도',
            '노선명',
            '역명',
            '승차총승객수',
            '하차총승객수'
        ]
    ]

    df_list.append(df)


# 모든 파일 통합
result = pd.concat(df_list, ignore_index=True)

# 확인
print(result.head())
print(result.shape)
print(result.columns)

CARD_SUBWAY_MONTH_2022.csv → cp949
CARD_SUBWAY_MONTH_202301.csv → utf-8-sig
CARD_SUBWAY_MONTH_202302.csv → utf-8-sig
CARD_SUBWAY_MONTH_202303.csv → utf-8-sig
CARD_SUBWAY_MONTH_202304.csv → utf-8-sig
CARD_SUBWAY_MONTH_202305.csv → utf-8-sig
CARD_SUBWAY_MONTH_202306.csv → utf-8-sig
CARD_SUBWAY_MONTH_202307.csv → utf-8-sig
CARD_SUBWAY_MONTH_202308.csv → utf-8-sig
CARD_SUBWAY_MONTH_202309.csv → utf-8-sig
CARD_SUBWAY_MONTH_202310.csv → utf-8-sig
CARD_SUBWAY_MONTH_202311.csv → utf-8-sig
CARD_SUBWAY_MONTH_202312.csv → utf-8-sig
CARD_SUBWAY_MONTH_202401.csv → utf-8-sig
CARD_SUBWAY_MONTH_202402.csv → cp949
CARD_SUBWAY_MONTH_202403.csv → utf-8-sig
CARD_SUBWAY_MONTH_202404.csv → utf-8-sig
CARD_SUBWAY_MONTH_202405.csv → utf-8-sig
CARD_SUBWAY_MONTH_202406.csv → utf-8-sig
CARD_SUBWAY_MONTH_202407.csv → utf-8-sig
CARD_SUBWAY_MONTH_202408.csv → utf-8-sig
CARD_SUBWAY_MONTH_202409.csv → utf-8-sig
CARD_SUBWAY_MONTH_202410.csv → utf-8-sig
CARD_SUBWAY_MONTH_202411.csv → utf-8-sig
CARD_SUBWAY_MONTH_202412.csv → utf-8-sig
CARD_SUBWAY_MONTH_202501.csv → utf-8-sig
CARD_SUBWAY_MONTH_202502.csv → cp949
CARD_SUBWAY_MONTH_202503.csv → utf-8-sig
CARD_SUBWAY_MONTH_202504.csv → utf-8-sig
CARD_SUBWAY_MONTH_202505.csv → utf-8-sig
CARD_SUBWAY_MONTH_202506.csv → utf-8-sig
CARD_SUBWAY_MONTH_202507.csv → utf-8-sig
CARD_SUBWAY_MONTH_202508.csv → utf-8-sig
CARD_SUBWAY_MONTH_202509.csv → utf-8-sig
CARD_SUBWAY_MONTH_202510.csv → utf-8-sig
CARD_SUBWAY_MONTH_202511.csv → utf-8-sig
CARD_SUBWAY_MONTH_202512.csv → utf-8-sig
CARD_SUBWAY_MONTH_202601.csv → utf-8-sig
CARD_SUBWAY_MONTH_202602.csv → utf-8-sig
CARD_SUBWAY_MONTH_202603.csv → utf-8-sig
CARD_SUBWAY_MONTH_202604.csv → utf-8-sig
CARD_SUBWAY_MONTH_202605.csv → utf-8-sig
CARD_SUBWAY_MONTH_202606.csv → utf-8-sig
CARD_SUBWAY_MONTH_202607.csv → utf-8-sig
~$CARD_SUBWAY_MONTH_2022.csv → utf-8-sig
노선명 없음 → ~$CARD_SUBWAY_MONTH_2022.csv
~$CARD_SUBWAY_MONTH_202301.csv → utf-8-sig
노선명 없음 → ~$CARD_SUBWAY_MONTH_202301.csv
     연도  노선명           역명  승차총승객수  하차총승객수
0  2022  2호선      구로디지털단지   18363   18352
1  2022  2호선          신대방   11652   11727
2  2022  2호선           신림   29564   29162
3  2022  2호선           봉천    9207    8941
4  2022  2호선  서울대입구(관악구청)   20142   20315
(83650, 5)
Index(['연도', '노선명', '역명', '승차총승객수', '하차총승객수'], dtype='str')

In [44]:
result.head()

     연도  노선명           역명  승차총승객수  하차총승객수
0  2022  2호선      구로디지털단지   18363   18352
1  2022  2호선          신대방   11652   11727
2  2022  2호선           신림   29564   29162
3  2022  2호선           봉천    9207    8941
4  2022  2호선  서울대입구(관악구청)   20142   20315

In [45]:
result.to_csv(
    'C:/Users/user/Desktop/데이터들/subway/subway_2호선_통합.csv',
    index=False,
    encoding='utf-8-sig'
)

In [46]:
result['역명'].unique()

<StringArray>
[       '구로디지털단지',            '신대방',             '신림',             '봉천',
    '서울대입구(관악구청)',       '낙성대(강감찬)',             '사당',             '방배',
             '서초',     '교대(법원.검찰청)',             '강남',             '역삼',
             '선릉',       '삼성(무역센터)',          '종합운동장',           '잠실새내',
       '잠실(송파구청)',           '잠실나루',     '강변(동서울터미널)',       '구의(광진구청)',
           '건대입구',             '성수',             '뚝섬',            '한양대',
      '왕십리(성동구청)',           '상왕십리',             '신당', '동대문역사문화공원(DDP)',
          '을지로4가',          '을지로3가',          '을지로입구',             '시청',
             '이대',             '신촌',           '홍대입구',             '합정',
             '당산',          '영등포구청',             '문래',            '신도림',
       '대림(구로구청)',             '아현',     '충정로(경기대입구)',             '용답',
             '신답',            '신설동',            '도림천',           '양천구청',
          '신정네거리',      '용두(동대문구청)']
Length: 50, dtype: str

In [49]:
result['역명'] = (
    result['역명']
    .str.replace(r'\(.*\)', '', regex=True)
    .str.strip()
)

# 사용할 역 목록
target_stations = [
    '용두',
    '교대',
    '신도림',
    '잠실나루',
    '신대방',
    '성수',
    '왕십리',
    '삼성',
    '봉천',
    '강남',
    '당산',
    '양천구청',
    '사당',
    '신당',
    '잠실',
    '신림',
    '방배',
    '구의',
    '건대입구',
    '구로디지털단지',
    '대림',
    '아현',
    '영등포구청',
    '이대',
    '합정',
    '문래',
    '한양대',
    '시청',
    '상왕십리',
    '신설동',
    '용답',
    '홍대입구',
    '충정로'
]

# 원하는 역만 추출
result = result[
    result['역명'].isin(target_stations)
].copy()

# 확인
print(result['역명'].unique())
print('역 개수:', result['역명'].nunique())

<StringArray>
['구로디지털단지',     '신대방',      '신림',      '봉천',      '사당',      '방배',      '교대',
      '강남',      '삼성',      '잠실',    '잠실나루',      '구의',    '건대입구',      '성수',
     '한양대',     '왕십리',    '상왕십리',      '신당',      '시청',      '이대',    '홍대입구',
      '합정',      '당산',   '영등포구청',      '문래',     '신도림',      '대림',      '아현',
     '충정로',      '용답',     '신설동',    '양천구청',      '용두']
Length: 33, dtype: str
역 개수: 33

In [50]:
result.to_csv(
    'C:/Users/user/Desktop/데이터들/subway/subway_2호선_통합(역제거).csv',
    index=False,
    encoding='utf-8-sig'
)

In [57]:
apt = pd.read_excel('C:/Users/user/Desktop/데이터들/아파트_매매_33역.xlsx')
apt.head()

   역명  계약연월   거래금액 주택유형
0  시청  2025  27000  아파트
1  시청  2025  27000  아파트
2  시청  2025  27000  아파트
3  시청  2024  55000  아파트
4  시청  2024  55000  아파트

In [58]:
apt['역명'].unique()

<StringArray>
[     '시청',      '신당',    '상왕십리',     '왕십리',     '한양대',      '성수',      '용답',
      '용두',     '신설동',    '건대입구',      '구의',    '잠실나루',      '잠실',      '삼성',
      '강남',      '교대',      '방배',      '사당',      '봉천',      '신림',     '신대방',
 '구로디지털단지',      '대림',     '신도림',    '양천구청',      '문래',   '영등포구청',      '당산',
      '합정',    '홍대입구',      '이대',      '아현',     '충정로']
Length: 33, dtype: str

In [59]:
set(apt['역명'].unique()) - set(result['역명'].unique())

set()

In [56]:
mon['역명'] = (
    mon['역명']
    .str.replace(r'\(.*\)', '', regex=True)
    .str.strip()
)

# 사용할 역 목록
target_stations = [
    '용두',
    '교대',
    '신도림',
    '잠실나루',
    '신대방',
    '성수',
    '왕십리',
    '삼성',
    '봉천',
    '강남',
    '당산',
    '양천구청',
    '사당',
    '신당',
    '잠실',
    '신림',
    '방배',
    '구의',
    '건대입구',
    '구로디지털단지',
    '대림',
    '아현',
    '영등포구청',
    '이대',
    '합정',
    '문래',
    '한양대',
    '시청',
    '상왕십리',
    '신설동',
    '용답',
    '홍대입구',
    '충정로'
]

# 원하는 역만 추출
mon = mon[
    mon['역명'].isin(target_stations)
].copy()

# 확인
print(mon['역명'].unique())
print('역 개수:', mon['역명'].nunique())

<StringArray>
[     '강남',      '삼성',      '봉천',      '신림',    '건대입구',      '구의', '구로디지털단지',
     '신도림',      '용두',     '신설동',      '사당',    '홍대입구',      '아현',      '합정',
      '이대',     '충정로',      '방배',      '교대',      '용답',     '왕십리',     '한양대',
      '성수',    '상왕십리',    '잠실나루',    '양천구청',      '대림',   '영등포구청',      '문래',
      '신당',      '시청']
Length: 30, dtype: str
역 개수: 30